# Generated by Django 3.0.4 on 2020-06-10 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='added',
        ),
    ]
