# Generated by Django 3.0.4 on 2020-06-10 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('thumbnail', models.ImageField(upload_to='portfolio/images/')),
                ('description', models.TextField(max_length=1000)),
                ('details', models.TextField(blank=True, max_length=10000)),
                ('screenshot_main', models.ImageField(blank=True, upload_to='portfolio/images/')),
                ('screenshot_1', models.ImageField(blank=True, upload_to='portfolio/images/')),
                ('screenshot_2', models.ImageField(blank=True, upload_to='portfolio/images/')),
                ('screenshot_3', models.ImageField(blank=True, upload_to='portfolio/images/')),
                ('created', models.DateTimeField(blank=True)),
                ('url_github', models.URLField(blank=True)),
                ('url_live', models.URLField(blank=True)),
            ],
        ),
    ]
