# Generated by Django 3.0.5 on 2020-06-13 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='screenshot_1',
            field=models.ImageField(blank=True, null=True, upload_to='portfolio/images/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='screenshot_2',
            field=models.ImageField(blank=True, null=True, upload_to='portfolio/images/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='screenshot_3',
            field=models.ImageField(blank=True, null=True, upload_to='portfolio/images/'),
        ),
    ]
